### ISSUE TITLE
Validate after Download

### ISSUE THREAD

**Issue by mastafrooper** [fmd-project-team/FMD#8]
It's not super regular but occasionally, normally when downloading a large series, some cbz files are corrupt.

Was wondering if at some point in the future an option could be added to validate the zip/cbz when it is finished and if corrupted redownload/recompress before moving on.

**Comment by SDXC** [comment]
Do you mean the file packing mechanism of FMD itself or do you download cbz from the website? Is the archive itself corrupt or just some images?

This corruption should be fixable if it's being zipped after the download.

**Comment by mastafrooper** [comment]
The packaging mechanism of FMD itself.

The archive itself is corrupt. If you run a test on it with 7zip the error is: 'Unexpected End of Archive' and it won't open with any readers. Tell it to download the chapters again and it works fine.

FMD is running in a VM saving to a network location. That location is on the host machine though so there should be no network drops.

**Comment by SDXC** [comment]
Okay, thanks for the reply. That's a bug then.

It either could be fixed with a new version of 7za (if it is the problem) or by fixing the way FMD writes the files to the archive or moves the archive (if it does). It can actually be a problem on the networking side, but more on the application layer than the actual network layer.

**Comment by SDXC** [comment]
I'll take validation for archives in as a feature request. It would be a new option next to the archiving option.

**Comment by mastafrooper** [comment]
Thanks. No hurry at all, it's been happening for a long time I've just been too lazy to log an issue. The move to a new fork kinda just motivated me some ;D

**Comment by SDXC** [comment]
@mastafrooper Please try this new version before I release it. It should now work.

[fmd_0.9.160.1.zip](https://github.com/fmd-project-team/FMD/files/3031421/fmd_0.9.160.1.zip)

-> It was Synapse which was a little bit too old. It's now the latest version.

**Comment by SDXC** [comment]
I have updated 7-Zip from 18.01 to 19.00. There were many bugfixes between them, so it's possible that it already fixes your problem. The new version of FMD will go public in the next hours. After the update please observe the behavior and let me know after some time, if it got any better, still the same or even worse.

On a side note: the new version of 7-Zip should be a little faster.

PS: Ticket won't be closed if this fixes your problem, as the validation part is still a good idea. It just won't be high priority.

**Comment by mastafrooper** [comment]
I'll give it a try when I get home from work... in like 8 hours.

The problem isn't super consistent so I'll give it a few days and maybe find a new series to download at the same time.

**Comment by SDXC** [comment]
Official release is out now. The updater in the version 0.9.160.0 doesn't work. You have to update manually. Updater should work for the future releases though.

**Comment by mastafrooper** [comment]
Problem is still occurring. It's random so I can't be certain but the only thing I can think of is when it is downloading when my Surface Go is turned on as it's set to sync my manga folders whenever there are changes.

It shouldn't be locking a temp file though unless FMD isn't locking it. It doesn't happen to every file though. This series I found had 14 chapters and it happened to 4. I also downloaded another 9 chapters of other stuff before that and all those files were fine.

`20:02:37:568 EFCreateError - DoZipCbz.Exception
Unable to create file "\\ABYSS-SVR\Data\Manga\To-Read\Maou-Sama Retry\0004 - Vol. 01 Ch. 004.tmp" (15 Items)
    $000000010004BAFB
    $000000010004B9F3
    $00000001004A9AB2
    $00000001004A9E10
    $00000001004A9CF2
    $00000001004A9C44
    $00000001004A5D08
    $00000001004A63D7
    $00000001002767A1
    $0000000100278CF5
    $0000000100053E9D
    $0000000100003B76
    $0000000100015047
    $00007FFE2B7E81F4
    $00007FFE2E26A271`

**Comment by SDXC** [comment]
Can you recreate this issue with the exact same series over and over again?
If we can recreate this more or less at will, we can test better.

Regarding the problem itself, here are some guesses:
* Your sync sets a lock on the image files and FMD/7-Zip can't get a read on them and aborts.
* Your sync also targets tmp files and locks them whil 7-Zip is packing or trying to rename the tmp to cbz.

Things to test:
* Disable the sync for a while and download/zip a passable amount of chapters. If no errors occur, it wasn't a networking issue, but because of a conflict with your sync tool.
* Download/zip the chapters locally.

Things to check on your side:
* Does your sync allow to use file filters? If yes, when you set a filter for cbz only, does the problem still occur?

Things to check on my side:
* Is a file lock being set by FMD? If not -> possible solution.

**Comment by mastafrooper** [comment]
Did some more testing last night.

Does seem to be the syncing that's causing the issue. Added exclusions to it for JPG, GIF, PNG and a few other image formats I could think of as well as TMP files. Also tweaked it's idle time to 60 seconds after last modification before it syncs. Still got the occasional corrupt CBZ. Shut the tablet down when I went to sleep and another 100-150 chapters of things downloaded without incident.

So it seems like the sync tool is whats causing FMD to not archive things correctly. Whether it is ignoring exclusions or it is locking something when it is checking timestamps etc I have no idea.

I suppose a file lock/temp file directory might sort the issue. Hardly a super important issue though since it is caused by my weird setup.

**Comment by SDXC** [comment]
So it's not an actual bug then.
I will implement an option to define a temp directory for chapter packing.
Meaning that chapters will be downloaded to temp, zipped, archive moved to actual target and temp will be cleared afterwards.

I will evaluate some more concepts though.

**Comment by mastafrooper** [comment]
Awesome. No hurry though as this is something normal people wont deal with ;D
